version: '3.7'
services:
  app:
    container_name: "app"
    image: app
    env_file:
      - settings_server.env
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/app/docker/app.sh"]
    ports:
      - "8000:8000"
    networks:
      - default